services:
  # Serviço do Nginx, responsável por receber as requisições HTTP
  nginx:
    # Imagem oficial do Nginx, baseada em Alpine Linux
    image: nginx:1.30-alpine3.23

    # Nome fixo do container para facilitar identificação e debug
    container_name: app_nginx

    # Mapeia a porta 8080 do host para a porta 80 do container
    # Permite acessar a aplicação via http://localhost:8080
    ports:
      - "80:80"

    # Volume que monta o arquivo de configuração do Nginx no container
    # O sufixo :ro indica que o arquivo será somente leitura
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/

    # Define que o container PHP deve ser iniciado antes do Nginx
    depends_on:
      - php

    # Conecta o container à rede interna do projeto
    networks:
      - app_network

  # Serviço do PHP, responsável por executar a aplicação
  php:
    #Define esse mesmo diretório como o ponto de execução padrão dentro do container, garantindo
    #que comandos como o Composer sejam executados no contexto correto do projeto, onde estão
    working_dir: /var/www
    # Define que a imagem será construída a partir de um Dockerfile
    build:
      # Contexto de build, normalmente a raiz do projeto
      context: .
      # Caminho do Dockerfile responsável por montar o ambiente PHP
      dockerfile: docker/php/Dockerfile

    # Nome fixo do container PHP
    container_name: app_php

    # Permite que o container acesse o VSCode no host para debug via Xdebug
    extra_hosts:
      - "host.docker.internal:host-gateway"

    #Permitindo que qualquer alteração feita no código no VS Code seja imediatamente refletida no ambiente Docker
    volumes:
      - ./:/var/www/

    command: >+
      sh -c "composer install --no-interaction &&
             composer dump-autoload -o &&
             php-fpm"

    # Variáveis de ambiente do container
    environment:
      # Define o fuso horário do container
      TZ: ${TZ}
      # Se APP_DEBUG tem valor no .env → XDEBUG_MODE=debug (ativo); se vazio → usa "off" do php.ini
      XDEBUG_MODE: ${APP_DEBUG:+debug}

    # Conecta o container à rede interna do projeto
    networks:
      - app_network

  # Serviço do banco de dados PostgreSQL
  postgres:
    # Imagem oficial do PostgreSQL baseada em Alpine Linux
    image: postgres:18.3-alpine3.23
    # Nome fixo do container do banco
    container_name: app_postgres
    restart: unless-stopped
    # Variáveis de ambiente usadas pelo PostgreSQL na inicialização
    environment:
      # Nome do banco de dados, vindo do arquivo .env
      POSTGRES_DB: ${DB_NAME}
      # Usuário do banco, vindo do arquivo .env
      POSTGRES_USER: ${DB_USER}
      # Senha do banco, vindo do arquivo .env
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      # Define o fuso horário do container
      TZ: ${TZ}
    # Volumes persistentes e scripts de inicialização
    volumes:
      # Volume nomeado para persistir os dados do banco
      - ./docker/postgres/storage:/var/lib/postgresql/18/docker
      # Script SQL executado automaticamente na primeira inicialização
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${DB_PORT}:${DB_PORT}"
    # Conecta o container à rede interna do projeto
    networks:
      - app_network

# Definição das redes do projeto
networks:
  # Rede bridge interna para comunicação entre os containers
  app_network:
    driver: bridge
